-- 코드를 작성해주세요
# FISH_INFO  -> ID, FISH_TYPE, LENGTH, TIME
# FISH_NAME_INFO -> FISH_TYPE, FISH_NAME 

SELECT COUNT(*) AS FISH_COUNT
FROM FISH_INFO
WHERE FISH_TYPE IN(
    SELECT FISH_TYPE 
    FROM FISH_NAME_INFO
    WHERE FISH_NAME IN('BASS','SNAPPER'))